Repository freelawproject/courtlistener, pull requests merged in 2025-06, with the labels that each got.

#5512 5477 Display Audio Transcripts on oral argument page
  cl/audio/static/js/transcript.js
  cl/audio/static/skin/transcript.css
  cl/audio/templates/oral_argument.html
  cl/audio/views.py
Labels: slow-review

#5298 Introduced Opinion nested embeddings field
  cl/search/documents.py
  cl/search/test_assets/opinion_1_embeddings.json
  cl/search/tests/tests_semantic_search_opinion.py
Labels: ready-to-merge

#5340 4560 Introduced cl_index_embeddings command
  cl/lib/search_index_utils.py
  cl/search/factories.py
  cl/search/management/commands/cl_index_embeddings.py
  cl/search/tasks.py
  cl/search/tests/tests_semantic_search_opinion.py
Labels: ready-to-merge

#5643 feat(templates): introduce header in new templates
  cl/assets/static-global/js/alpine/components/header.js
  cl/assets/static-global/svg/avatar.svg
  cl/assets/static-global/svg/avatar_outline.svg
  cl/assets/static-global/svg/bell.svg
  cl/assets/static-global/svg/bookmark.svg
  cl/assets/static-global/svg/brackets.svg
  cl/assets/static-global/svg/chevron.svg
  cl/assets/static-global/svg/code.svg
  cl/assets/static-global/svg/graph_up.svg
  cl/assets/static-global/svg/group.svg
  cl/assets/static-global/svg/logos/courtlistener.svg
  cl/assets/static-global/svg/magnifier.svg
  cl/assets/static-global/svg/money_hand.svg
  cl/assets/static-global/svg/sign_out.svg
  cl/assets/static-global/svg/tag.svg
  cl/assets/tailwind/input.css
  cl/assets/tailwind/tailwind.config.js
  cl/assets/templates/cotton/expansion_panel.html
  cl/assets/templates/cotton/footer.html
  cl/assets/templates/cotton/header.html
  cl/assets/templates/cotton/layout_with_navigation/index.html
  cl/assets/templates/cotton/navigation_menu.html
  cl/assets/templates/new_base.html
  cl/custom_filters/templatetags/svg_tags.py
  cl/lib/middleware.py
  cl/search/templates/v2_homepage.html
Labels: ready-to-merge

#5698 Removed RECAP Search Alerts "coming soon" references
  cl/api/templates/alert-api-docs-vlatest.html
  cl/simple_pages/templates/help/alert_help.html
  cl/simple_pages/templates/v2_help/alert_help.html
Labels: ready-to-merge

#5700 feat(search): Refines UI to edit alerts
  cl/alerts/templates/delete_confirm.html
  cl/alerts/views.py
  cl/search/templates/search.html
Labels: ready-to-merge

#5695 Jbgolds/5667 oral argument transcript revisions
  cl/audio/static/js/transcript.js
  cl/audio/static/skin/transcript.css
  cl/audio/templates/oral_argument.html
Labels: fast-review

#5747 feat(RECAP): restoring links to PACER for documents listed as unavailable on RECAP
  cl/assets/static-global/css/override.css
  cl/opinion_page/templates/includes/de_list.html
  cl/opinion_page/templates/includes/rd_download_button.html
Labels: slow-review

#5279 feat(merge_opinion_versions): new command
  cl/scrapers/management/commands/merge_opinion_versions.py
  cl/scrapers/tasks.py
  cl/scrapers/tests.py
  cl/search/docket_sources.py
  cl/search/migrations/0040_add_opinion_main_version_field.py
  cl/search/migrations/0040_add_opinion_main_version_field.sql
  cl/search/migrations/0040_add_opinion_main_version_field_customers.sql
  cl/search/models.py
Labels: ready-to-merge
