Repository freelawproject/courtlistener, pull requests merged in 2025-07, with the labels that each got.

#5808 feat(cl): Remove Twitter and replace with Bluesky
  cl/alerts/templates/alert_email_es.txt
  cl/alerts/templates/docket_alert_email.txt
  cl/alerts/templates/docket_alert_unsubscription_email.txt
  cl/alerts/templates/emails/old_alert_email.txt
  cl/alerts/templates/pacer_alert_email.txt
  cl/assets/templates/base.html
  cl/assets/templates/includes/social_links.html
  cl/favorites/templates/prayer_email.txt
  cl/favorites/templates/prayer_email_unavailable.txt
Labels: slow-review

#5940 fix(audio): Use select_related to join on the related Docket to preve…
  cl/audio/sitemap.py
  cl/lib/management/commands/make_dev_data.py
Labels: slow-review

#5958 Add deployment options
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/docker-build.yml
Labels: skip-celery-deploy, skip-web-deploy, skip-cronjob-deploy

#6012 refactor(pacer): rewrite do_pacer_fetch using match-case syntax
  cl/recap/tasks.py
  cl/settings/third_party/celery.py
Labels: skip-celery-deploy, skip-cronjob-deploy, skip-daemon-deploy

#6011 Adds new URL to monitor celery
  cl/settings/third_party/celery.py
  cl/simple_pages/tests.py
  cl/stats/urls.py
  cl/stats/views.py
Labels: skip-celery-deploy, skip-cronjob-deploy, skip-daemon-deploy

#6018 Use correct queue for feeds
  cl/corpus_importer/management/commands/upload_to_ia.py
  cl/recap/management/commands/nightly_pacer_updates.py
  cl/recap_rss/tasks.py
  cl/settings/third_party/celery.py
Labels: skip-web-deploy

#6007 fix(merge_opinion_versions): fix OpinionDocument ES removal
  cl/scrapers/management/commands/merge_opinion_versions.py
Labels: skip-web-deploy

#6024 feat(aws_manifest): Removes ocr_status filter from recap queries
  cl/corpus_importer/management/commands/make_aws_manifest_files.py
Labels: skip-celery-deploy, skip-cronjob-deploy, skip-daemon-deploy

#6026 5807 Introduced ASCIIUsernameValidator to protect against homoglyph attacks
  cl/users/forms.py
  cl/users/tests.py
Labels: skip-celery-deploy, skip-cronjob-deploy, skip-daemon-deploy

#5953 refactor(cl): refactored factories
  cl/alerts/factories.py
  cl/alerts/tests/tests.py
  cl/alerts/tests/tests_recap_alerts.py
  cl/api/factories.py
  cl/api/tests.py
  cl/audio/factories.py
  cl/citations/tests.py
  cl/corpus_importer/tests.py
  cl/lib/factories.py
  cl/lib/management/commands/make_dev_data.py
  cl/lib/test_helpers.py
  cl/lib/tests.py
  cl/opinion_page/tests.py
  cl/people_db/tests.py
  cl/recap/tests/tests.py
  cl/search/factories.py
  cl/search/tests/test_pacer_bulk_fetch.py
  cl/search/tests/test_search_signals.py
  cl/search/tests/tests.py
  cl/search/tests/tests_es_opinion.py
  cl/search/tests/tests_es_recap.py
Labels: skip-deploy

#6027 Ensure orchestration runs
  .github/workflows/docker-build.yml
Labels: skip-celery-deploy, skip-web-deploy, skip-cronjob-deploy

#6036 5947 Fixed API version links on the latest Webhook docs page
  cl/api/templates/webhooks-docs-vlatest.html
Labels: skip-celery-deploy, skip-cronjob-deploy, skip-daemon-deploy

#6037 5948 Log 'Error getting sweep alert index task status' as a warning
  cl/alerts/management/commands/cl_send_recap_alerts.py
Labels: skip-celery-deploy, skip-web-deploy, skip-daemon-deploy

#6023 feat(cl): Issue template for reporting bugs with labels
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
Labels: skip-deploy

#6049 fix(github): tweak issue template
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: skip-deploy

#6061 fix(unmatched_citations): Ignore conflict in unmatched citations
  cl/citations/unmatched_citations_utils.py
Labels: skip-web-deploy, skip-cronjob-deploy, skip-daemon-deploy

#5552 fix(docker compose): Required Dev Credential Handling Update
  docker/courtlistener/docker-compose.yml
Labels: skip-celery-deploy, skip-web-deploy, skip-deploy, skip-cronjob-deploy, skip-daemon-deploy

#5996 feat(search.models): add ClusterRedirection model
  cl/api/tests.py
  cl/assets/templates/410.html
  cl/opinion_page/decorators.py
  cl/opinion_page/tests.py
  cl/opinion_page/views.py
  cl/search/api_views.py
  cl/search/migrations/0041_add_cluster_redirection.py
  cl/search/migrations/0041_add_cluster_redirection.sql
  cl/search/models.py
Labels: skip-cronjob-deploy, skip-daemon-deploy

#6077 feat(search): Enhances semantic search with inner_hits, scoring, and chunk merging
  cl/lib/elasticsearch_utils.py
  cl/search/api_serializers.py
  cl/search/api_utils.py
  cl/search/api_views.py
  cl/search/tests/tests_semantic_search_opinion.py
Labels: skip-celery-deploy, skip-cronjob-deploy, skip-daemon-deploy

#6090 fix(PULL_REQUEST_TEMPLATE.md): add wiki link for skip-deploy labels
  .github/PULL_REQUEST_TEMPLATE.md
Labels: skip-deploy

#6079 refactor(find-citations): For large opinions chunk find citations
  cl/citations/annotate_citations.py
  cl/citations/recap_citations.py
  cl/citations/tasks.py
  cl/citations/tests.py
  cl/citations/utils.py
Labels: skip-daemon-deploy

#6073 fix(merge_opinion_versions): limit versioning to SOURCES.COURT_WEBSITE clusters
  cl/scrapers/management/commands/merge_opinion_versions.py
  cl/scrapers/tasks.py
  cl/scrapers/tests.py
Labels: skip-web-deploy, skip-daemon-deploy

#6092 feat(search): Adds KNN_OVERSAMPLE setting to k-NN query configuration
  cl/lib/elasticsearch_utils.py
  cl/settings/project/search.py
Labels: skip-celery-deploy, skip-cronjob-deploy, skip-daemon-deploy

#6094 5976 Updated API to v4.1
  cl/api/templates/case-law-api-docs-vlatest.html
  cl/api/templates/pacer-api-docs-vlatest.html
  cl/api/templates/rest-change-log.html
  cl/api/templates/rest-docs-vlatest.html
Labels: skip-celery-deploy, skip-cronjob-deploy, skip-daemon-deploy

#6097 feat(opinion): Enables view tracking for opinion views
  cl/favorites/api_serializers.py
  cl/opinion_page/templates/opinions.html
  cl/opinion_page/views.py
Labels: skip-celery-deploy, skip-deploy, skip-cronjob-deploy, skip-daemon-deploy

#6016 Update coverage_oa.html
  cl/simple_pages/templates/v2_help/coverage_oa.html
Labels: skip-celery-deploy, skip-deploy, skip-cronjob-deploy, skip-daemon-deploy
