Repository freelawproject/courtlistener, pull requests merged in 2025-09, with the labels that each got.

#6244 fix(new_homepage): handle empty queryset in DB when aggregating mins of OA
  cl/search/utils.py
Labels: skip-celery-deploy, skip-cronjob-deploy, skip-daemon-deploy

#6250 feat(docs): update API version to v4.3 in documentation
  cl/api/templates/rest-change-log.html
  cl/api/templates/rest-docs-vlatest.html
Labels: skip-celery-deploy, skip-web-deploy, skip-deploy, skip-cronjob-deploy, skip-daemon-deploy

#6249 Restrict V4 API endpoints to authenticated users
  cl/api/api_permissions.py
  cl/api/tests.py
  cl/search/api_views.py
Labels: skip-celery-deploy, skip-cronjob-deploy, skip-daemon-deploy

#6252 fix(docs): Update throttling details
  cl/api/templates/rest-docs-vlatest.html
Labels: skip-celery-deploy, skip-cronjob-deploy, skip-daemon-deploy

#6257 fix(bulk-data): Replaces `apt-key` with keyrings for PostgreSQL
  scripts/make_bulk_data.sh
Labels: skip-celery-deploy, skip-web-deploy, skip-daemon-deploy

#6262 feat(help_pages): tweak bulk data docs to highlight that files are snapshots
  cl/api/templates/bulk-data.html
  cl/api/templates/v2_bulk-data.html
Labels: skip-celery-deploy, skip-cronjob-deploy, skip-daemon-deploy

#6261 fix(coverage_utils): handle court with no courthouse
  cl/search/models.py
  cl/search/signals.py
  cl/simple_pages/coverage_utils.py
Labels: skip-celery-deploy, skip-cronjob-deploy, skip-daemon-deploy

#6275 fix(recap_into_opinions): remove flat=True in values_list()
  cl/corpus_importer/management/commands/recap_into_opinions.py
Labels: skip-celery-deploy, skip-web-deploy, skip-cronjob-deploy, skip-daemon-deploy

#6263 Add webhook link to top of alert docs
  cl/simple_pages/templates/help/alert_help.html
  cl/simple_pages/templates/v2_help/alert_help.html
Labels: skip-deploy

#6305 refactor(donate): Adds missing membership levels and refactor constants
  cl/alerts/constants.py
  cl/alerts/tests/tests.py
  cl/alerts/tests/tests_recap_alerts.py
  cl/donate/api_views.py
  cl/donate/migrations/0012_add_missing_membership_levels_noop.py
  cl/donate/migrations/0012_add_missing_membership_levels_noop.sql
  cl/donate/models.py
  cl/donate/tests.py
  cl/favorites/tests.py
Labels: skip-celery-deploy, skip-cronjob-deploy, skip-daemon-deploy

#6311 feat(search): Add opinion embeddings generation and caching
  cl/lib/es_signal_processor.py
  cl/lib/microservice_utils.py
  cl/scrapers/tests.py
  cl/search/models.py
  cl/search/signals.py
  cl/search/tasks.py
  cl/search/tests/tests_es_opinion.py
  cl/settings/project/microservices.py
  cl/settings/project/search.py
Labels: skip-deploy, skip-cronjob-deploy, skip-daemon-deploy

#6332 fix(merge_opinion_versions): make text similarity threshold more flexible
  cl/scrapers/management/commands/merge_opinion_versions.py
  cl/scrapers/tests.py
Labels: skip-web-deploy, skip-daemon-deploy
