Repository freelawproject/courtlistener, pull requests merged in 2025-08, with the labels that each got.

#6125 Remove style attrs and tweak words
  cl/opinion_page/templates/includes/rd_metadata_headers.html
Labels: skip-celery-deploy, skip-cronjob-deploy, skip-daemon-deploy

#6130 fix(recap): Replaces undefined `context` attribute with `context_data`
  cl/opinion_page/templates/includes/rd_metadata_headers.html
  cl/opinion_page/views.py
Labels: skip-celery-deploy, skip-cronjob-deploy, skip-daemon-deploy

#6122 refactor(search): Narrows keyword matching in semantic queries to 'text' field
  cl/lib/elasticsearch_utils.py
  cl/search/tests/tests_semantic_search_opinion.py
Labels: skip-celery-deploy, skip-cronjob-deploy, skip-daemon-deploy

#6088 fix(merge_opinion_versions): delete objects related to citation annotation
  cl/citations/management/commands/find_citations.py
  cl/scrapers/management/commands/merge_opinion_versions.py
  cl/scrapers/tests.py
Labels: skip-web-deploy, skip-daemon-deploy

#6100 feat(search): Adds support for unlimited search alerts
  cl/alerts/forms.py
  cl/alerts/management/commands/cl_send_alerts.py
  cl/alerts/management/commands/cl_send_recap_alerts.py
  cl/alerts/tasks.py
  cl/alerts/templates/includes/search_alerts/table_row.html
  cl/alerts/tests/tests.py
  cl/alerts/tests/tests_recap_alerts.py
  cl/assets/static-global/js/search-alerts.js
  cl/search/views.py
  cl/users/models.py
  cl/users/templates/profile/alerts.html
Labels: skip-daemon-deploy

#6140 6038 Set expiration time for scrape_rss task chain
  cl/recap_rss/management/commands/scrape_rss.py
Labels: skip-web-deploy, skip-cronjob-deploy

#6139 6118 Make decay relevance scores for Search API cursor pagination results stable
  cl/lib/elasticsearch_utils.py
  cl/search/tests/tests_es_recap.py
Labels: skip-celery-deploy, skip-cronjob-deploy, skip-daemon-deploy

#6136 feat(scrapers): create OriginatingCourtInformation objects from scrapers
  cl/corpus_importer/management/commands/import_tn.py
  cl/opinion_page/forms.py
  cl/scrapers/management/commands/cl_scrape_opinions.py
  cl/scrapers/test_assets/test_opinion_scraper.py
  cl/scrapers/test_assets/test_opinion_site.xml
  cl/scrapers/tests.py
  cl/scrapers/utils.py
Labels: skip-celery-deploy, skip-web-deploy, skip-daemon-deploy

#6141 Tweak PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: skip-deploy

#6142 feat(search): Estimate available document count using statistics
  cl/search/selectors.py
  cl/simple_pages/templates/faq.html
  cl/simple_pages/views.py
Labels: skip-celery-deploy, skip-cronjob-deploy, skip-daemon-deploy

#6152 6006 Removed search micro cache outdated code
  cl/lib/search_utils.py
Labels: skip-celery-deploy, skip-cronjob-deploy, skip-daemon-deploy

#6155 6154 Added the total results count to the Opinions home page cached object
  cl/lib/search_utils.py
  cl/search/tests/tests_es_opinion.py
Labels: skip-celery-deploy, skip-cronjob-deploy, skip-daemon-deploy

#6162 feat(docket): Requires User Authentication for CSV Exports
  cl/opinion_page/templates/includes/de_list.html
  cl/opinion_page/tests.py
  cl/opinion_page/views.py
Labels: skip-celery-deploy, skip-cronjob-deploy, skip-daemon-deploy

#6153 feat(memberships): Adds validations for .edu accounts
  cl/donate/api_views.py
  cl/donate/tests.py
  cl/users/utils.py
Labels: skip-celery-deploy, skip-cronjob-deploy, skip-daemon-deploy

#6172 Add admin page for ClusterRedirection model
  cl/search/admin.py
Labels: skip-celery-deploy, skip-cronjob-deploy, skip-daemon-deploy

#6171 fix(delete_duplicates): handle versioned cluster
  cl/scrapers/management/commands/delete_duplicates.py
Labels: skip-celery-deploy, skip-web-deploy, skip-cronjob-deploy, skip-daemon-deploy

#6174 fix(count_citations): citation_count update is now done in batches
  cl/citations/management/commands/count_citations.py
  cl/citations/tests.py
Labels: skip-celery-deploy, skip-web-deploy, skip-cronjob-deploy, skip-daemon-deploy

#6183 fix(new_homepage): tweak copy to accurately describe the stat displayed
  cl/search/templates/v2_homepage.html
Labels: skip-celery-deploy, skip-cronjob-deploy, skip-daemon-deploy

#6184 fix(count_citations): remove nargs from ids fields
  cl/citations/management/commands/count_citations.py
Labels: skip-celery-deploy, skip-web-deploy, skip-cronjob-deploy, skip-daemon-deploy

#6185 fix(count_citations): use proper indexes in loop
  cl/citations/management/commands/count_citations.py
Labels: skip-celery-deploy, skip-web-deploy, skip-cronjob-deploy, skip-daemon-deploy

#6189 feat(api): block user
  cl/settings/third_party/rest_framework.py
Labels: skip-celery-deploy, skip-cronjob-deploy, skip-daemon-deploy

#6193 fix(opinions): Adds `rel="nofollow"` to Filter Similar Cases link
  cl/opinion_page/templates/includes/opinion_tabs_content.html
Labels: skip-celery-deploy, skip-cronjob-deploy, skip-daemon-deploy

#6170 feat(profile): Add profile page with user's CL ID
  cl/users/templates/profile/cl_id.html
  cl/users/urls.py
  cl/users/views.py
Labels: skip-celery-deploy, skip-cronjob-deploy, skip-daemon-deploy

#6196 feat(delete_duplicates): add cluster-sources optional arg
  cl/scrapers/management/commands/delete_duplicates.py
  cl/scrapers/tests.py
Labels: skip-celery-deploy, skip-web-deploy, skip-cronjob-deploy, skip-daemon-deploy

#5639 fix(opinion_page.views): optimize `get_opinions_base_queryset`
  cl/opinion_page/templates/opinions.html
  cl/opinion_page/views.py
Labels: skip-celery-deploy, skip-cronjob-deploy, skip-daemon-deploy

#6218 feat(api): Block user
  cl/settings/third_party/rest_framework.py
Labels: skip-celery-deploy, skip-cronjob-deploy, skip-daemon-deploy

#6221 fix(recap_into_opinions): improve duplicated hash checks
  cl/corpus_importer/management/commands/recap_into_opinions.py
  cl/corpus_importer/management/commands/scrape_pacer_free_opinions.py
  cl/corpus_importer/tasks.py
Labels: skip-deploy

#6200 Set default values for statistics
  cl/search/selectors.py
  cl/search/utils.py
Labels: skip-celery-deploy, skip-deploy, skip-cronjob-deploy, skip-daemon-deploy

#6220 feat(components): introduce date selector sub-component for the Corpus Search component
  cl/assets/static-global/css/third_party/README.md
  cl/assets/static-global/css/third_party/flatpickr.css
  cl/assets/static-global/js/alpine/README.md
  cl/assets/static-global/js/alpine/components/corpus_search.js
  cl/assets/static-global/js/alpine/components/date_selector.js
  cl/assets/static-global/js/alpine/composables/focus.js
  cl/assets/static-global/js/third_party/README.md
  cl/assets/static-global/js/third_party/flatpickr/flatpickr@4.6.13.js
  cl/assets/static-global/js/third_party/flatpickr/flatpickr@4.6.13.min.js
  cl/assets/static-global/js/third_party/flatpickr/plugins/confirmDate@4.6.13.js
  cl/assets/static-global/js/third_party/flatpickr/plugins/confirmDate@4.6.13.min.js
  cl/assets/tailwind/input.css
  cl/search/templates/cotton/corpus_search/date_selector/index.html
  cl/search/templates/cotton/corpus_search/date_selector/relative_date_option.html
  cl/search/templates/cotton/corpus_search/filters/index.html
  cl/search/templates/cotton/corpus_search/filters/judges.html
  cl/search/templates/cotton/corpus_search/filters/opinions.html
  cl/search/templates/cotton/corpus_search/filters/oral_arguments.html
  cl/search/templates/cotton/corpus_search/filters/recap.html
  cl/search/templates/cotton/corpus_search/mobile/dialog.html
Labels: skip-celery-deploy, skip-cronjob-deploy, skip-daemon-deploy

#6177 feat(citations): command to reindex_es_cite_fields
  cl/citations/management/commands/reindex_es_cite_fields.py
  cl/citations/tests.py
  cl/search/tasks.py
Labels: skip-web-deploy, skip-cronjob-deploy, skip-daemon-deploy

#6223 feat(donate): Adds `payment_status` to NeonMembership model
  cl/donate/api_views.py
  cl/donate/migrations/0011_add_payment_status_to_neonmembership.py
  cl/donate/migrations/0011_add_payment_status_to_neonmembership.sql
  cl/donate/migrations/0011_add_payment_status_to_neonmembership_customers.sql
  cl/donate/models.py
  cl/donate/tests.py
Labels: skip-celery-deploy, skip-cronjob-deploy, skip-daemon-deploy

#6236 feat(update_from_text): now handles OriginatingCourtInformation
  cl/scrapers/management/commands/update_from_text.py
  cl/scrapers/tasks.py
  cl/scrapers/test_assets/test_opinion_scraper.py
  cl/scrapers/tests.py
Labels: skip-web-deploy, skip-daemon-deploy
